/* =====================================================================================================================
   LOOPDOKU CORE  v1  (shared by every competition entry; paste it inline into your single HTML file, do not edit it)
   A RoxorLoops & Jasmin take on Meowdoku / Queens: put one performer in every row, every column and every coloured
   region, and performers may never touch, not even at a corner.

   WHAT YOU GET (everything hangs off window.LD)
     LD.PUZZLES[k]            {id, index, n, rows, sol, region (flat array of region numbers), diff, city, venue, country}
     LD.DEFAULT_PUZZLE        index of the 7x7 showcase puzzle
     new LD.Game(puzzle|index|id, opts?)   the rules + state; emits events your renderer turns into juice
     LD.bindInput(el, game, {cellAt(clientX, clientY) -> index | -1, onCursor?(i), keyboard?})   tap / drag / double-tap / long-press / keys
     LD.audio                 synthesized beatbox + voice sound kit (WebAudio, no files)  LD.audio.attach(game) = default sounds for every event
     LD.loop                  the Loop Station: a 96 BPM groove that gains one layer per performer placed; LD.loop.on(fn) beat callbacks
     LD.demo(game, hooks)     scripted autoplay that shows every interaction (taps, a drag, a mistake, a hint, the win)
     LD.shaker(el, opts)      decaying-trauma screen shake for a wrapper element   LD.ease.*   easing curves

   CELL VALUES  game.cells[i]: LD.CELL.EMPTY 0, CROSS 1 (player's X), AUTO 2 (X added by the game around a performer), PIECE 3
                game.wrong[i] = 1 when that X was left behind by a mistake (draw it red-ish)
   INDEXING     i = r * n + c, row r top to bottom, column c left to right.  game.rc(i) -> {r, c}  game.idx(r, c)
   WHO          game.who(i) -> 'roxor' (even rows) | 'jasmin' (odd rows): which performer stands on a placed cell

   EVENTS (game.on(type, fn); game.on('*', fn) gets every event as fn(type, data))
     'mark'    {i, r, c, value, on, source, k, delay, dist, from}
               on = the cell now shows an X.  source: 'tap' | 'drag' | 'line' | 'auto' | 'undo' | 'clear' | 'revert' | 'mistake' | 'hint'
               k = order inside a drag stroke or an auto-cross cascade (use it to raise the pitch / stagger),
               delay = suggested ms before you animate it (auto cascades ripple outward from `from`), dist = rings from `from`
     'place'   {i, r, c, who, count, total, byHint}          a correct performer lands (it is locked in for good)
     'mistake' {i, r, c, lives, mistakes}                   wrong cell: a life is lost, the cell becomes a red X
     'blocked' {i, by}                                      tried to place on a cell already crossed by performer `by` (no penalty)
     'locked'  {i}                                          tapped a performer (they are locked; give a little wobble)
     'line'    {kind: 'row' | 'col', index, mode: 'mark' | 'erase', count, cells}  an arrow crossed out (or wiped) a whole line
     'stroke'  {mode: 'mark' | 'erase', count}              a drag finished
     'layer'   {count, total}                               the Loop Station gained a layer (after every place)
     'hint'    {kind: 'place' | 'cross', i, unit, unitKind} the hint the game just applied (unit = the cells that explain it)
     'undo'    {count}   'clear' {count}   'reset' {}   'start' {}   'win' {ms, mistakes, hints, stars}   'lose' {ms}
     'cursor'  {i}  (keyboard focus moved)

   GAME METHODS  crossLine('row' | 'col', index)  lineHasEmpty(kind, index)  tap(i)  place(i)  doubleTap(i)  revertLastTap(i)  beginStroke(i)  paintEnter(i)  paintEnd()  undo()
                 clearCrosses()  hint()  reset()  elapsed() (ms)  peers(i)  stars()  isSolution(i)  regionCells(k)  rowCells(r)  colCells(c)
                 pieceAttacking(i) (index of a placed performer that rules i out, or -1)  nextDeduction()  units()
   OPTIONS       {autoCross: false (true = the game crosses out everything a performer rules out), lives: 3 (0 = relaxed, no lives), doubleTapMs: 320, longPressMs: 430}
   ===================================================================================================================== */
(function () {
  'use strict';
  const LD = (window.LD = window.LD || {});
  LD.VERSION = 1;

  // ------------------------------------------------------------------------------------------------------------------
  // PUZZLES (generated by gen_puzzles.mjs: unique solution, solvable by logic alone, no guessing)
  // ------------------------------------------------------------------------------------------------------------------
  const RAW = [{"n":5,"rows":["AABBB","AABBC","ADBBC","ADBBC","ADECC"],"sol":[0,3,1,4,2],"hard":0},{"n":5,"rows":["ABBBB","BBBBB","CCCDD","ECCEE","EEEEE"],"sol":[0,2,4,1,3],"hard":2},{"n":6,"rows":["ABBBBC","ABBBBC","AADEEC","AAEEFF","EEEFFF","EEEEFF"],"sol":[3,5,2,0,4,1],"hard":4},{"n":6,"rows":["ABBBBB","AAABBB","AAACCB","DEEFCB","EEEFBB","EEFFBB"],"sol":[5,2,4,0,3,1],"hard":5},{"n":7,"rows":["AABBCCC","DACCCCC","DDCCCEE","DDDCCEE","DDDDFFE","GDDDEEE","GGGEEEE"],"sol":[3,1,4,2,5,0,6],"hard":4},{"n":7,"rows":["ABCCDDD","BBCCDDE","BBCCCDD","FFCCCCD","FFFCDDD","FFFGGDD","FFFFGGD"],"sol":[0,6,1,3,5,2,4],"hard":3},{"n":7,"rows":["ABBBBBC","BBBBBCC","DDDDDCC","EEDDDEF","EEEEEEF","EEEGFFF","EEEEFFF"],"sol":[0,2,6,4,1,3,5],"hard":6},{"n":8,"rows":["ABBBBBCC","ADDDBBEE","AADDDBEF","AADDDFFF","AAGDFFFF","HGGDDGFF","HHGGGGGG","HHGGGGGG"],"sol":[7,4,6,1,5,3,0,2],"hard":9},{"n":8,"rows":["AAAAABBB","AAAAABBB","ACCCCBBB","ACCCDDDB","ACEDDDDB","CCEDDDFB","CEEGGHFB","GGGGGHBB"],"sol":[0,7,1,4,2,6,3,5],"hard":15},{"n":9,"rows":["AAAAAABBB","CAAAABBBB","CCCCCBBBB","CCDCCBBBB","CCEEEBBBF","CCEEEBFFF","CCEEEGHHF","CCEEGGGFF","EEEIIGGFF"],"sol":[1,6,0,2,8,4,7,5,3],"hard":17}];
  const GIGS = [
    { city: 'Copenhagen', venue: 'Harbour Stage', country: 'DK' },
    { city: 'Aarhus', venue: 'Confirmation Party', country: 'DK' },
    { city: 'Odense', venue: 'Wedding Reception', country: 'DK' },
    { city: 'Berlin', venue: 'Club Night', country: 'DE' },
    { city: 'Brussels', venue: 'Street Festival', country: 'BE' },
    { city: 'Amsterdam', venue: 'Canal Boat Gig', country: 'NL' },
    { city: 'Paris', venue: 'Rooftop Session', country: 'FR' },
    { city: 'Stockholm', venue: 'Corporate Gala', country: 'SE' },
    { city: 'Athens', venue: 'Open-Air Theatre', country: 'GR' },
    { city: 'Quito', venue: 'World Tour Finale', country: 'EC' },
  ];
  const DIFF = { 5: 'Easy', 6: 'Normal', 7: 'Normal', 8: 'Hard', 9: 'Extreme' };
  // turn {n, rows, sol} into a playable puzzle object (adds region[]); extra fields (id, city, venue, diff...) are merged in
  LD.makePuzzle = function (p, extra) {
    const region = [];
    for (const row of p.rows) for (const ch of row) region.push(ch.charCodeAt(0) - 65);
    return Object.assign({ n: p.n, rows: p.rows, sol: p.sol, region, diff: DIFF[p.n] || 'Hard' }, extra || {});
  };
  LD.GIGS = GIGS;
  LD.PUZZLES = RAW.map((p, k) => LD.makePuzzle(p, Object.assign({ id: 'gig' + (k + 1), index: k }, GIGS[k] || { city: 'Encore', venue: 'Bonus', country: '' })));
  LD.DEFAULT_PUZZLE = Math.max(0, LD.PUZZLES.findIndex((p) => p.n === 7));

  const CELL = (LD.CELL = { EMPTY: 0, CROSS: 1, AUTO: 2, PIECE: 3 });
  const now = () => (typeof performance !== 'undefined' ? performance.now() : Date.now());

  // ------------------------------------------------------------------------------------------------------------------
  // GAME
  // ------------------------------------------------------------------------------------------------------------------
  function Game(p, opts) {
    if (typeof p === 'number') p = LD.PUZZLES[p];
    else if (typeof p === 'string') p = LD.PUZZLES.find((q) => q.id === p);
    if (!p) p = LD.PUZZLES[LD.DEFAULT_PUZZLE];
    if (!p.region) p = LD.makePuzzle(p, p);
    this.p = p; this.n = p.n; this.N = p.n * p.n; this.region = p.region;
    this.opts = Object.assign({ autoCross: false, lives: 3, doubleTapMs: 320, longPressMs: 430 }, opts || {});
    this.solSet = new Set(p.sol.map((c, r) => r * p.n + c));
    this.handlers = {};
    this.reset();
  }
  const G = Game.prototype;
  G.on = function (type, fn) { (this.handlers[type] = this.handlers[type] || []).push(fn); return this; };
  G.off = function (type, fn) { const h = this.handlers[type]; if (h) this.handlers[type] = h.filter((f) => f !== fn); return this; };
  G.emit = function (type, data) {
    const d = data || {};
    for (const f of this.handlers[type] || []) { try { f(d); } catch (e) { console.error('LD handler', type, e); } }
    for (const f of this.handlers['*'] || []) { try { f(type, d); } catch (e) { console.error('LD handler *', e); } }
  };
  G.reset = function () {
    this.cells = new Uint8Array(this.N); this.wrong = new Uint8Array(this.N);
    this.lives = this.opts.lives; this.mistakes = 0; this.hints = 0; this.placed = 0;
    this.over = false; this.won = false; this.t0 = null; this.tEnd = null;
    this.undoStack = []; this.stroke = null; this.lastTap = null;
    this.emit('reset', {});
  };
  G.rc = function (i) { return { r: (i / this.n) | 0, c: i % this.n }; };
  G.idx = function (r, c) { return r * this.n + c; };
  G.who = function (i) { return ((i / this.n) | 0) % 2 === 0 ? 'roxor' : 'jasmin'; };
  G.isSolution = function (i) { return this.solSet.has(i); };
  G.rowCells = function (r) { const a = []; for (let c = 0; c < this.n; c++) a.push(r * this.n + c); return a; };
  G.colCells = function (c) { const a = []; for (let r = 0; r < this.n; r++) a.push(r * this.n + c); return a; };
  G.regionCells = function (k) { const a = []; for (let i = 0; i < this.N; i++) if (this.region[i] === k) a.push(i); return a; };
  G.units = function () {
    if (this._units) return this._units;
    const u = [];
    for (let r = 0; r < this.n; r++) u.push({ kind: 'row', index: r, cells: this.rowCells(r) });
    for (let c = 0; c < this.n; c++) u.push({ kind: 'col', index: c, cells: this.colCells(c) });
    for (let k = 0; k < this.n; k++) u.push({ kind: 'region', index: k, cells: this.regionCells(k) });
    return (this._units = u);
  };
  G.attacks = function (i, j) {
    if (i === j) return false;
    const n = this.n, ri = (i / n) | 0, ci = i % n, rj = (j / n) | 0, cj = j % n;
    return ri === rj || ci === cj || this.region[i] === this.region[j] || (Math.abs(ri - rj) <= 1 && Math.abs(ci - cj) <= 1);
  };
  G.dist = function (i, j) { const a = this.rc(i), b = this.rc(j); return Math.max(Math.abs(a.r - b.r), Math.abs(a.c - b.c)); };
  // every cell a performer on i rules out, nearest first (the order of the auto-cross ripple)
  G.peers = function (i) {
    const out = [];
    for (let j = 0; j < this.N; j++) if (this.attacks(i, j)) out.push(j);
    out.sort((a, b) => this.dist(i, a) - this.dist(i, b) || a - b);
    return out;
  };
  G.pieceAttacking = function (i) {
    for (let j = 0; j < this.N; j++) if (this.cells[j] === CELL.PIECE && this.attacks(j, i)) return j;
    return -1;
  };
  G.elapsed = function () { if (this.t0 === null) return 0; return (this.tEnd !== null ? this.tEnd : now()) - this.t0; };
  G._start = function () { if (this.t0 === null) { this.t0 = now(); this.emit('start', {}); } };
  G._mark = function (i, value, extra) {
    this.cells[i] = value;
    const rc = this.rc(i);
    this.emit('mark', Object.assign({ i, r: rc.r, c: rc.c, value, on: value === CELL.CROSS || value === CELL.AUTO, source: 'tap', k: 0, delay: 0, dist: 0, from: -1 }, extra || {}));
  };

  G.tap = function (i) {
    if (this.over || i < 0 || i >= this.N) return false;
    this._start();
    const v = this.cells[i];
    if (v === CELL.PIECE) { this.emit('locked', { i }); this.lastTap = null; return false; }
    const to = v === CELL.EMPTY ? CELL.CROSS : CELL.EMPTY;
    const wasWrong = this.wrong[i];
    if (to === CELL.EMPTY) this.wrong[i] = 0;
    this.undoStack.push([{ i, from: v, to, wrong: wasWrong }]);
    this.lastTap = { i, prev: v, wrong: wasWrong, time: now() };
    this._mark(i, to, { source: 'tap' });
    return true;
  };
  G.revertLastTap = function (i) {
    const t = this.lastTap;
    if (!t || t.i !== i) return false;
    this.lastTap = null;
    const top = this.undoStack[this.undoStack.length - 1];
    if (top && top.length === 1 && top[0].i === i) this.undoStack.pop();
    this.wrong[i] = t.wrong;
    this._mark(i, t.prev, { source: 'revert' });
    return true;
  };
  // second tap on the same cell inside opts.doubleTapMs: undo the first tap's X and drop a performer
  G.doubleTap = function (i) {
    const t = this.lastTap;
    if (!t || t.i !== i || now() - t.time > this.opts.doubleTapMs) return false;
    this.revertLastTap(i);
    this.place(i);
    return true;
  };
  G.place = function (i, byHint) {
    if (this.over || i < 0 || i >= this.N || this.cells[i] === CELL.PIECE) return false;
    this._start();
    this.lastTap = null;
    if (this.cells[i] === CELL.AUTO) { this.emit('blocked', { i, by: this.pieceAttacking(i) }); return false; }
    const rc = this.rc(i);
    if (!this.isSolution(i)) {
      this.mistakes++;
      if (this.opts.lives > 0) this.lives = Math.max(0, this.lives - 1);
      this.wrong[i] = 1;
      this._mark(i, CELL.CROSS, { source: 'mistake' });
      this.emit('mistake', { i, r: rc.r, c: rc.c, lives: this.lives, mistakes: this.mistakes });
      if (this.opts.lives > 0 && this.lives === 0) { this.over = true; this.tEnd = now(); this.emit('lose', { ms: this.elapsed() }); }
      return false;
    }
    this.cells[i] = CELL.PIECE; this.wrong[i] = 0; this.placed++;
    if (byHint) this.hints++;
    this.emit('place', { i, r: rc.r, c: rc.c, who: this.who(i), count: this.placed, total: this.n, byHint: !!byHint });
    if (this.opts.autoCross) {
      let k = 0;
      for (const j of this.peers(i)) {
        if (this.cells[j] !== CELL.EMPTY) continue;
        const d = this.dist(i, j);
        this._mark(j, CELL.AUTO, { source: 'auto', k, dist: d, from: i, delay: 70 + d * 55 + (k % 4) * 8 });
        k++;
      }
    }
    // undo entries can never resurrect an X under a performer
    for (const batch of this.undoStack) for (const e of batch) if (e.i === i) e.dead = true;
    this.emit('layer', { count: this.placed, total: this.n });
    if (this.placed === this.n) {
      this.over = true; this.won = true; this.tEnd = now();
      this.emit('win', { ms: this.elapsed(), mistakes: this.mistakes, hints: this.hints, stars: this.stars() });
    }
    return true;
  };
  G.stars = function () { let s = 3; if (this.mistakes > 0) s--; if (this.mistakes > 1) s--; if (this.hints > 0) s--; return Math.max(1, s); };

  // drag painting: the input layer taps the first cell, then calls beginStroke(firstCell) when the finger leaves it
  G.beginStroke = function (i) {
    if (this.over) return;
    const t = this.lastTap;
    const mode = t && t.i === i ? (t.prev === CELL.EMPTY ? 'mark' : 'erase') : (this.cells[i] === CELL.EMPTY ? 'mark' : 'erase');
    let batch = [];
    const top = this.undoStack[this.undoStack.length - 1];
    if (t && t.i === i && top && top.length === 1 && top[0].i === i) batch = this.undoStack.pop();
    this.stroke = { mode, k: 1, seen: new Set([i]), batch };
    this.lastTap = null;
  };
  G.paintEnter = function (i) {
    const s = this.stroke;
    if (!s || this.over || i < 0 || i >= this.N || s.seen.has(i)) return;
    s.seen.add(i);
    const v = this.cells[i];
    if (s.mode === 'mark' && v === CELL.EMPTY) {
      s.batch.push({ i, from: v, to: CELL.CROSS, wrong: 0 });
      this._mark(i, CELL.CROSS, { source: 'drag', k: s.k++ });
    } else if (s.mode === 'erase' && (v === CELL.CROSS || v === CELL.AUTO)) {
      s.batch.push({ i, from: v, to: CELL.EMPTY, wrong: this.wrong[i] });
      this.wrong[i] = 0;
      this._mark(i, CELL.EMPTY, { source: 'drag', k: s.k++ });
    }
  };
  G.paintEnd = function () {
    const s = this.stroke;
    if (!s) return;
    this.stroke = null;
    if (s.batch.length) this.undoStack.push(s.batch);
    this.emit('stroke', { mode: s.mode, count: s.batch.length });
  };
  G.undo = function () {
    if (this.over) return 0;
    const batch = this.undoStack.pop();
    if (!batch) { this.emit('undo', { count: 0 }); return 0; }
    let k = 0;
    for (let n = batch.length - 1; n >= 0; n--) {
      const e = batch[n];
      if (e.dead || this.cells[e.i] !== e.to) continue;
      this.wrong[e.i] = e.wrong || 0;
      this._mark(e.i, e.from, { source: 'undo', k: k++, delay: k * 18 });
    }
    this.lastTap = null;
    this.emit('undo', { count: k });
    return k;
  };
  // the row / column arrows: cross out every empty square of a line in one go (a wave along the line, k = order, delay = stagger).
  // If the line has no empty square left, the arrow wipes that line's own X's instead (red mistake X's stay). Emits 'line'.
  G.crossLine = function (kind, index) {
    if (this.over) return 0;
    this._start();
    const cells = kind === 'col' ? this.colCells(index) : this.rowCells(index);
    const empty = cells.filter((i) => this.cells[i] === CELL.EMPTY);
    const batch = [];
    let k = 0, mode = 'mark';
    if (empty.length) {
      for (const i of empty) { batch.push({ i, from: CELL.EMPTY, to: CELL.CROSS, wrong: 0 }); this._mark(i, CELL.CROSS, { source: 'line', k, delay: k * 35 }); k++; }
    } else {
      mode = 'erase';
      for (const i of cells) {
        if ((this.cells[i] !== CELL.CROSS && this.cells[i] !== CELL.AUTO) || this.wrong[i]) continue;
        batch.push({ i, from: this.cells[i], to: CELL.EMPTY, wrong: 0 }); this._mark(i, CELL.EMPTY, { source: 'line', k, delay: k * 35 }); k++;
      }
    }
    if (batch.length) this.undoStack.push(batch);
    this.lastTap = null;
    this.emit('line', { kind, index, mode, count: k, cells });
    return k;
  };
  // true when a line still has an empty square (arrows can show a "ready" state)
  G.lineHasEmpty = function (kind, index) { return (kind === 'col' ? this.colCells(index) : this.rowCells(index)).some((i) => this.cells[i] === CELL.EMPTY); };
  G.clearCrosses = function () {
    if (this.over) return 0;
    const batch = [];
    let k = 0;
    for (let i = 0; i < this.N; i++) {
      if (this.cells[i] !== CELL.CROSS || this.wrong[i]) continue;
      batch.push({ i, from: CELL.CROSS, to: CELL.EMPTY, wrong: 0 });
      this._mark(i, CELL.EMPTY, { source: 'clear', k, delay: k * 22 });
      k++;
    }
    if (batch.length) this.undoStack.push(batch);
    this.lastTap = null;
    this.emit('clear', { count: k });
    return k;
  };

  // the logical picture: a cell is open when no performer rules it out and it is not a correct X
  G._open = function () {
    const open = new Uint8Array(this.N);
    for (let i = 0; i < this.N; i++) {
      if (this.cells[i] === CELL.PIECE) continue;
      if (this.pieceAttacking(i) >= 0) continue;
      if ((this.cells[i] === CELL.CROSS) && !this.isSolution(i)) continue;
      open[i] = 1;
    }
    return open;
  };
  // the next deduction a human could make. Returns {kind, i, unit, unitKind} or null
  G.nextDeduction = function () {
    const open = this._open();
    const units = this.units().filter((u) => !u.cells.some((i) => this.cells[i] === CELL.PIECE));
    for (const u of units) {
      const o = u.cells.filter((i) => open[i]);
      if (o.length === 1) return { kind: 'place', i: o[0], unit: u.cells, unitKind: u.kind };
    }
    for (let i = 0; i < this.N; i++) {
      if (!open[i] || this.cells[i] !== CELL.EMPTY) continue;
      for (const u of units) {
        if (u.cells.includes(i)) continue;
        if (u.cells.every((j) => !open[j] || this.attacks(i, j))) return { kind: 'cross', i, unit: u.cells, unitKind: u.kind };
      }
    }
    for (let r = 0; r < this.n; r++) {
      const i = r * this.n + this.p.sol[r];
      if (this.cells[i] !== CELL.PIECE) return { kind: 'place', i, unit: this.rowCells(r), unitKind: 'row' };
    }
    return null;
  };
  G.hint = function () {
    if (this.over) return null;
    const d = this.nextDeduction();
    if (!d) return null;
    this.emit('hint', d);
    if (d.kind === 'place') {
      if (this.cells[d.i] !== CELL.EMPTY) { this.wrong[d.i] = 0; this._mark(d.i, CELL.EMPTY, { source: 'hint' }); }
      this.place(d.i, true);
    } else {
      this.hints++;
      this.undoStack.push([{ i: d.i, from: CELL.EMPTY, to: CELL.CROSS, wrong: 0 }]);
      this._mark(d.i, CELL.CROSS, { source: 'hint' });
    }
    return d;
  };
  LD.Game = Game;

  // ------------------------------------------------------------------------------------------------------------------
  // INPUT: press a cell = X appears instantly (on press, not release). Slide = paint X's (or erase if you started on an X).
  // Second press on the same cell within doubleTapMs, a long press, or a right click = drop a performer.
  // Keys: arrows move the cursor, Space/X = cross, Enter/P = performer, Z or Backspace = undo, H = hint.
  // ------------------------------------------------------------------------------------------------------------------
  LD.bindInput = function (el, game, o) {
    o = o || {};
    const cellAt = o.cellAt;
    let down = null, cursor = -1;
    el.style.touchAction = 'none';
    el.style.userSelect = 'none';
    el.style.webkitUserSelect = 'none';
    el.style.webkitTouchCallout = 'none';
    const g = () => (typeof game === 'function' ? game() : game);
    function setCursor(i) {
      cursor = i;
      if (o.onCursor) o.onCursor(i);
      g().emit('cursor', { i });
    }
    function onDown(e) {
      LD.audio.unlock();
      const gm = g();
      const i = cellAt(e.clientX, e.clientY);
      if (i < 0 || gm.over) return;
      e.preventDefault();
      try { el.setPointerCapture(e.pointerId); } catch (_) { /* ignore */ }
      if (e.button === 2) { gm.place(i); down = null; return; }
      if (gm.doubleTap(i)) { down = { i, id: e.pointerId, consumed: true }; return; }
      gm.tap(i);
      down = { i, id: e.pointerId, last: i, drag: false, consumed: false, timer: 0 };
      down.timer = setTimeout(() => {
        if (down && !down.drag && !down.consumed && down.i === i) {
          down.consumed = true;
          gm.revertLastTap(i);
          gm.place(i);
        }
      }, gm.opts.longPressMs);
    }
    function onMove(e) {
      if (o.onHover && !down) o.onHover(cellAt(e.clientX, e.clientY));
      if (!down || down.consumed || e.pointerId !== down.id) return;
      const j = cellAt(e.clientX, e.clientY);
      if (j < 0 || j === down.last) return;
      const gm = g();
      if (!down.drag) { down.drag = true; clearTimeout(down.timer); gm.beginStroke(down.i); }
      down.last = j;
      gm.paintEnter(j);
    }
    function onUp(e) {
      if (!down || (down.id !== undefined && e.pointerId !== down.id)) return;
      clearTimeout(down.timer);
      if (down.drag) g().paintEnd();
      down = null;
    }
    function onKey(e) {
      const gm = g();
      const n = gm.n;
      if (e.target && /input|textarea|select/i.test(e.target.tagName)) return;
      let c = cursor < 0 ? Math.floor(n * n / 2) : cursor;
      const k = e.key;
      if (k === 'ArrowUp' || k === 'ArrowDown' || k === 'ArrowLeft' || k === 'ArrowRight') {
        if (cursor >= 0) {
          let r = (c / n) | 0, cc = c % n;
          if (k === 'ArrowUp') r = (r + n - 1) % n;
          if (k === 'ArrowDown') r = (r + 1) % n;
          if (k === 'ArrowLeft') cc = (cc + n - 1) % n;
          if (k === 'ArrowRight') cc = (cc + 1) % n;
          c = r * n + cc;
        }
        setCursor(c); e.preventDefault(); return;
      }
      LD.audio.unlock();
      if (k === ' ' || k === 'x' || k === 'X') { if (cursor < 0) setCursor(c); gm.tap(c); e.preventDefault(); }
      else if (k === 'Enter' || k === 'p' || k === 'P') { if (cursor < 0) setCursor(c); gm.place(c); e.preventDefault(); }
      else if (k === 'z' || k === 'Z' || k === 'Backspace') { gm.undo(); e.preventDefault(); }
      else if (k === 'h' || k === 'H') { gm.hint(); e.preventDefault(); }
    }
    const ctx = (e) => { if (cellAt(e.clientX, e.clientY) >= 0) e.preventDefault(); };
    el.addEventListener('pointerdown', onDown);
    el.addEventListener('pointermove', onMove);
    el.addEventListener('pointerup', onUp);
    el.addEventListener('pointercancel', onUp);
    el.addEventListener('lostpointercapture', onUp);
    el.addEventListener('contextmenu', ctx);
    if (o.keyboard !== false) window.addEventListener('keydown', onKey);
    return {
      setCursor,
      get cursor() { return cursor; },
      destroy() {
        el.removeEventListener('pointerdown', onDown); el.removeEventListener('pointermove', onMove);
        el.removeEventListener('pointerup', onUp); el.removeEventListener('pointercancel', onUp);
        el.removeEventListener('lostpointercapture', onUp); el.removeEventListener('contextmenu', ctx);
        window.removeEventListener('keydown', onKey);
      },
    };
  };

  // ------------------------------------------------------------------------------------------------------------------
  // AUDIO: "100% organic music with the human voice". Every sound is a synthesized beatbox hit or a sung vowel.
  //   LD.audio.unlock()  (call from a user gesture; bindInput does it for you)   .muted   .setMuted(b)   .volume (0..1)
  //   Drums (Roxor's mouth):  kick(v)  snare(v)  hat(v, open)  clap(v)  rim(v)  scratch(v)
  //   Voice (Jasmin's):       vox(midi, dur, {vowel:'oo'|'ah'|'ee'|'oh', vol, vib, at})   chord(midis, dur, vowel)
  //   Game sounds:            tick(k) (an X, pitch rises with k)  untick(k)  ripple(k, dist) (auto X)  pop(k)  thud()  ui()  uiBack()
  //                           place(who, count)  mistake()  blocked()  hint()  win()  lose()  whoosh()  sparkle()
  //   LD.audio.attach(game, {skip: ['mark', ...]}) wires the default sound to every event. Use it, then replace what you want.
  // ------------------------------------------------------------------------------------------------------------------
  const A = (LD.audio = { ctx: null, master: null, muted: false, volume: 0.8 });
  const PENTA = [0, 2, 4, 7, 9];
  const midiHz = (m) => 440 * Math.pow(2, (m - 69) / 12);
  const pent = (base, k) => base + PENTA[((k % 5) + 5) % 5] + 12 * Math.floor(k / 5);
  A.midiHz = midiHz; A.pent = pent;
  A.unlock = function () {
    if (!A.ctx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      try {
        A.ctx = new AC();
        A.comp = A.ctx.createDynamicsCompressor();
        A.comp.threshold.value = -14; A.comp.ratio.value = 4; A.comp.attack.value = 0.003; A.comp.release.value = 0.15;
        A.master = A.ctx.createGain();
        A.master.gain.value = A.muted ? 0 : A.volume;
        A.master.connect(A.comp); A.comp.connect(A.ctx.destination);
        const len = A.ctx.sampleRate;
        A.noiseBuf = A.ctx.createBuffer(1, len, A.ctx.sampleRate);
        const d = A.noiseBuf.getChannelData(0);
        let s = 12345;
        for (let i = 0; i < len; i++) { s = (s * 1103515245 + 12345) & 0x7fffffff; d[i] = (s / 0x3fffffff) - 1; }
      } catch (e) { A.ctx = null; return null; }
    }
    if (A.ctx.state === 'suspended') A.ctx.resume();
    return A.ctx;
  };
  A.setMuted = function (b) { A.muted = !!b; if (A.master) A.master.gain.value = A.muted ? 0 : A.volume; };
  A.setVolume = function (v) { A.volume = Math.max(0, Math.min(1, v)); if (A.master && !A.muted) A.master.gain.value = A.volume; };
  const T = (at) => (at !== undefined ? at : A.ctx.currentTime + 0.005);
  function env(g, t, a, peak, dur, curve) {
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), t + a);
    g.gain.exponentialRampToValueAtTime(0.0001, t + a + dur * (curve || 1));
  }
  function tone(type, f0, f1, t, dur, vol, dest) {
    const o = A.ctx.createOscillator(), g = A.ctx.createGain();
    o.type = type; o.frequency.setValueAtTime(f0, t);
    if (f1 && f1 !== f0) o.frequency.exponentialRampToValueAtTime(Math.max(1, f1), t + dur);
    env(g, t, 0.003, vol, dur);
    o.connect(g); g.connect(dest || A.master);
    o.start(t); o.stop(t + dur + 0.05);
    return o;
  }
  function noise(t, dur, vol, ftype, freq, q, dest) {
    const s = A.ctx.createBufferSource(); s.buffer = A.noiseBuf;
    s.playbackRate.value = 0.8 + ((t * 977) % 0.4);
    const f = A.ctx.createBiquadFilter(); f.type = ftype || 'highpass'; f.frequency.value = freq || 6000; f.Q.value = q || 0.7;
    const g = A.ctx.createGain(); env(g, t, 0.002, vol, dur);
    s.connect(f); f.connect(g); g.connect(dest || A.master);
    s.start(t, (t * 0.37) % 0.5); s.stop(t + dur + 0.05);
  }
  const ok = () => !!(A.ctx || A.unlock()) && !!A.master;
  // ---- beatbox drums ----
  A.kick = function (v, at) { if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v; tone('sine', 150, 42, t, 0.32, 0.9 * v); tone('triangle', 420, 90, t, 0.03, 0.25 * v); noise(t, 0.012, 0.25 * v, 'lowpass', 2500); };
  A.snare = function (v, at) { if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v; noise(t, 0.16, 0.55 * v, 'bandpass', 2200, 0.9); tone('triangle', 240, 150, t, 0.07, 0.3 * v); noise(t + 0.01, 0.08, 0.2 * v, 'highpass', 7000); };
  A.hat = function (v, open, at) { if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v; noise(t, open ? 0.22 : 0.045, 0.32 * v, 'highpass', 8200, 1.2); };
  A.clap = function (v, at) { if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v; for (let k = 0; k < 3; k++) noise(t + k * 0.012, 0.05, 0.3 * v, 'bandpass', 1500, 1.4); noise(t + 0.036, 0.18, 0.3 * v, 'bandpass', 1300, 1); };
  A.rim = function (v, at) { if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v; tone('square', 1700, 1400, t, 0.025, 0.12 * v); noise(t, 0.02, 0.2 * v, 'bandpass', 4000, 3); };
  A.scratch = function (v, at) {
    if (!ok()) return; const t = T(at); v = v === undefined ? 1 : v;
    const s = A.ctx.createBufferSource(); s.buffer = A.noiseBuf;
    const f = A.ctx.createBiquadFilter(); f.type = 'bandpass'; f.Q.value = 6;
    f.frequency.setValueAtTime(600, t); f.frequency.exponentialRampToValueAtTime(3200, t + 0.09); f.frequency.exponentialRampToValueAtTime(400, t + 0.26);
    const g = A.ctx.createGain(); env(g, t, 0.01, 0.6 * v, 0.28);
    s.connect(f); f.connect(g); g.connect(A.master); s.start(t); s.stop(t + 0.32);
  };
  // ---- the voice: a sawtooth through two vowel formants, with vibrato ----
  const VOWELS = { oo: [320, 800], oh: [450, 850], ah: [760, 1150], ee: [290, 2200], mm: [250, 600] };
  A.vox = function (midi, dur, o) {
    if (!ok()) return; o = o || {};
    const t = T(o.at), f0 = midiHz(midi), d = dur || 0.4, vol = o.vol === undefined ? 0.5 : o.vol;
    const src = A.ctx.createOscillator(); src.type = 'sawtooth'; src.frequency.setValueAtTime(f0 * 0.985, t); src.frequency.exponentialRampToValueAtTime(f0, t + 0.05);
    const lfo = A.ctx.createOscillator(), lg = A.ctx.createGain(); lfo.frequency.value = 5.4; lg.gain.setValueAtTime(0, t); lg.gain.linearRampToValueAtTime(f0 * (o.vib === undefined ? 0.012 : o.vib), t + d * 0.6);
    lfo.connect(lg); lg.connect(src.frequency);
    const fm = VOWELS[o.vowel || 'oo'] || VOWELS.oo, out = A.ctx.createGain();
    env(out, t, 0.03, vol, d, 1);
    for (let k = 0; k < 2; k++) { const bp = A.ctx.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.value = fm[k]; bp.Q.value = k ? 9 : 5; const gg = A.ctx.createGain(); gg.gain.value = k ? 0.5 : 1; src.connect(bp); bp.connect(gg); gg.connect(out); }
    const air = A.ctx.createOscillator(); air.type = 'sine'; air.frequency.value = f0; const ag = A.ctx.createGain(); ag.gain.value = 0.35; air.connect(ag); ag.connect(out);
    out.connect(A.master);
    [src, lfo, air].forEach((x) => { x.start(t); x.stop(t + d + 0.1); });
  };
  A.chord = function (midis, dur, vowel, at) { midis.forEach((m, k) => A.vox(m, dur, { vowel, vol: 0.28, at: at !== undefined ? at + k * 0.02 : undefined })); };
  // ---- game sounds ----
  A.tick = function (k) { if (!ok()) return; const t = T(); k = k || 0; noise(t, 0.035, 0.32, 'highpass', 7000 + Math.min(k, 12) * 200); tone('sine', midiHz(pent(76, k)), midiHz(pent(76, k)) * 0.98, t, 0.07, 0.22); };
  A.untick = function (k) { if (!ok()) return; const t = T(); k = k || 0; tone('triangle', midiHz(pent(67, -k)), midiHz(pent(64, -k)), t, 0.06, 0.16); noise(t, 0.02, 0.12, 'bandpass', 2500, 2); };
  A.ripple = function (k, dist, at) { if (!ok()) return; const t = T(at); const m = pent(81, (dist || 0) + (k || 0) % 2); tone('sine', midiHz(m), midiHz(m), t, 0.05, 0.08); };
  A.pop = function (k) { if (!ok()) return; const t = T(); const m = pent(72, k || 0); tone('sine', midiHz(m) * 0.6, midiHz(m), t, 0.09, 0.3); };
  A.thud = function () { if (!ok()) return; const t = T(); tone('sine', 120, 70, t, 0.12, 0.4); noise(t, 0.03, 0.15, 'lowpass', 900); };
  A.ui = function () { if (!ok()) return; const t = T(); tone('sine', 520, 880, t, 0.06, 0.25); A.hat(0.4); };
  A.uiBack = function () { if (!ok()) return; const t = T(); tone('sine', 700, 380, t, 0.07, 0.22); };
  A.whoosh = function () { if (!ok()) return; const t = T(); const s = A.ctx.createBufferSource(); s.buffer = A.noiseBuf; const f = A.ctx.createBiquadFilter(); f.type = 'bandpass'; f.Q.value = 1.4; f.frequency.setValueAtTime(400, t); f.frequency.exponentialRampToValueAtTime(4000, t + 0.25); const g = A.ctx.createGain(); env(g, t, 0.08, 0.35, 0.22); s.connect(f); f.connect(g); g.connect(A.master); s.start(t); s.stop(t + 0.4); };
  A.sparkle = function () { if (!ok()) return; const t = T(); [88, 91, 95, 100].forEach((m, k) => tone('sine', midiHz(m), midiHz(m), t + k * 0.045, 0.12, 0.1)); };
  // Roxor lands with a beatbox fill, Jasmin lands with a sung note; both climb the scale as the board fills
  A.place = function (who, count) {
    if (!ok()) return; const t = T(); count = count || 1;
    if (who === 'roxor') { A.kick(1, t); A.hat(0.6, false, t + 0.09); A.snare(0.8, t + 0.15); A.vox(pent(52, count), 0.18, { vowel: 'mm', vol: 0.3, at: t + 0.02 }); }
    else { A.vox(pent(69, count), 0.42, { vowel: 'oo', vol: 0.5, at: t }); A.vox(pent(69, count) + 7, 0.3, { vowel: 'ah', vol: 0.18, at: t + 0.08 }); A.hat(0.4, true, t); }
  };
  A.mistake = function () { if (!ok()) return; const t = T(); A.scratch(0.9, t); A.vox(50, 0.35, { vowel: 'oh', vol: 0.35, vib: 0.03, at: t + 0.12 }); A.vox(49, 0.35, { vowel: 'oh', vol: 0.25, at: t + 0.12 }); };
  A.blocked = function () { if (!ok()) return; A.thud(); A.rim(0.5); };
  A.hint = function () { A.sparkle(); if (ok()) A.vox(81, 0.3, { vowel: 'ee', vol: 0.2 }); };
  A.win = function () {
    if (!ok()) return; const t = T();
    A.kick(1, t); A.clap(0.8, t + 0.25); A.kick(1, t + 0.375); A.snare(1, t + 0.5);
    [[57, 60, 64], [60, 64, 67], [64, 67, 72, 76]].forEach((ch, k) => A.chord(ch, k === 2 ? 1.6 : 0.3, k === 2 ? 'ah' : 'oo', t + 0.12 + k * 0.25));
    A.sparkle();
  };
  A.lose = function () { if (!ok()) return; const t = T(); A.scratch(1, t); [60, 58, 55, 50].forEach((m, k) => A.vox(m, 0.32, { vowel: 'oh', vol: 0.35, at: t + 0.2 + k * 0.22 })); };
  A.attach = function (game, o) {
    const skip = new Set((o && o.skip) || []);
    const on = (type, fn) => { if (!skip.has(type)) game.on(type, fn); };
    on('mark', (e) => {
      if (e.source === 'tap' || e.source === 'drag') (e.on ? A.tick(e.k) : A.untick(e.k));
      else if (e.source === 'line') { if (A.ctx) { const at = A.ctx.currentTime + e.delay / 1000; if (e.on) A.ripple(e.k, e.k % 3, at); else A.ripple(e.k, 0, at); } }
      else if (e.source === 'auto') { if (A.ctx && e.k < 24) A.ripple(e.k, e.dist, A.ctx.currentTime + e.delay / 1000); }
      else if (e.source === 'undo') A.untick(e.k);
      else if (e.source === 'clear' && e.k % 2 === 0 && A.ctx) A.ripple(e.k, 0, A.ctx.currentTime + e.delay / 1000);
    });
    on('place', (e) => A.place(e.who, e.count));
    on('mistake', () => A.mistake());
    on('blocked', () => A.blocked());
    on('locked', () => A.thud());
    on('hint', () => A.hint());
    on('win', () => A.win());
    on('lose', () => A.lose());
    on('undo', () => A.uiBack());
    on('line', (e) => { if (e.count) A.whoosh(); });
  };

  // ------------------------------------------------------------------------------------------------------------------
  // THE LOOP STATION: a looping 4-bar groove (Am F C G, 96 BPM). Layers switch on one by one as performers land:
  //   1 kick, 2 hats, 3 snare, 4 bass, 5 vocal pad, 6 shaker, 7 lead "ooh" hook, 8 clap ghost notes, 9 vocal chops.
  //   LD.loop.start()  .stop()  .setLayers(n)  .bpm  .playing  .layers  .silent (true = keep the beat callbacks, play no sound)
  //   LD.loop.on(fn)   fn({step, beat, bar, downbeat, time}) at every 16th note, timed to the audio (also runs without audio)
  //   LD.loop.LAYER_NAMES   names for your Loop Station HUD, e.g. a lit pad or track per layer
  //   LD.loop.attach(game)  starts the groove on the first move, follows 'layer', goes full on win, stops on lose/reset
  // ------------------------------------------------------------------------------------------------------------------
  const L = (LD.loop = { bpm: 96, layers: 0, playing: false, step: 0, fns: [], LAYER_NAMES: ['Kick', 'Hats', 'Snare', 'Bass', 'Pad', 'Shaker', 'Hook', 'Claps', 'Chops'] });
  const PROG = [[57, 60, 64], [53, 57, 60], [48, 52, 55], [55, 59, 62]];
  const BASS = [45, 41, 36, 43];
  const HOOK = [76, null, 74, 72, null, 69, null, 72, 74, null, 76, null, 72, null, null, null];
  let timer = 0, nextT = 0, clockAudio = false;
  const clock = () => (A.ctx && A.ctx.state === 'running' ? A.ctx.currentTime : now() / 1000);
  L.on = function (fn) { L.fns.push(fn); return () => { L.fns = L.fns.filter((f) => f !== fn); }; };
  L.setLayers = function (n) { L.layers = Math.max(0, Math.min(9, n | 0)); };
  function playStep(s, t) {
    const bar = Math.floor(s / 16) % 4, q = s % 16, n = L.layers, audio = clockAudio && !A.muted && !L.silent;
    if (audio) {
      if (n >= 1 && (q === 0 || q === 8 || q === 10)) A.kick(q === 10 ? 0.7 : 1, t);
      if (n >= 2 && q % 2 === 0) A.hat(q % 4 === 2 ? 0.55 : 0.3, q === 14, t);
      if (n >= 3 && (q === 4 || q === 12)) A.snare(0.8, t);
      if (n >= 4 && (q === 0 || q === 6 || q === 10)) tone('triangle', midiHz(BASS[bar]), midiHz(BASS[bar]), t, 0.22, 0.32);
      if (n >= 5 && q === 0) A.chord(PROG[bar], 60 / L.bpm * 3.6, 'oo', t);
      if (n >= 6 && q % 2 === 1) noise(t, 0.03, 0.12, 'highpass', 9500);
      if (n >= 7 && HOOK[q] && (bar === 1 || bar === 3)) A.vox(HOOK[q] - (bar === 3 ? 2 : 0), 0.2, { vowel: 'oo', vol: 0.22, at: t });
      if (n >= 8 && (q === 7 || q === 15)) A.clap(0.35, t);
      if (n >= 9 && (q === 3 || q === 11) && bar % 2 === 0) A.vox(PROG[bar][2] + 12, 0.09, { vowel: 'ah', vol: 0.2, at: t });
    }
    const delay = Math.max(0, (t - clock()) * 1000);
    const info = { step: s, q, beat: Math.floor(q / 4), bar, downbeat: q === 0, onBeat: q % 4 === 0, time: t };
    setTimeout(() => { for (const f of L.fns) { try { f(info); } catch (e) { console.error(e); } } }, delay);
  }
  function pump() {
    const ahead = clock() + 0.12, stepDur = 60 / L.bpm / 4;
    const audioNow = !!(A.ctx && A.ctx.state === 'running');
    if (audioNow !== clockAudio) { clockAudio = audioNow; nextT = clock() + 0.03; }
    while (nextT < ahead) { playStep(L.step, nextT); L.step++; nextT += stepDur; }
  }
  L.start = function () {
    if (L.playing) return;
    L.playing = true; L.step = 0; clockAudio = !!(A.ctx && A.ctx.state === 'running'); nextT = clock() + 0.05;
    timer = setInterval(pump, 25); pump();
  };
  L.stop = function () { L.playing = false; clearInterval(timer); timer = 0; };
  L.attach = function (game) {
    game.on('start', () => { L.setLayers(Math.max(L.layers, 1)); L.start(); });
    game.on('layer', (e) => L.setLayers(Math.max(1, Math.round(1 + (e.count / e.total) * 8 - 0.0001))));
    game.on('win', () => L.setLayers(9));
    game.on('lose', () => { L.setLayers(0); L.stop(); });
    game.on('reset', () => { L.setLayers(0); });
  };

  // ------------------------------------------------------------------------------------------------------------------
  // DEMO: scripted autoplay through the SAME game methods a player uses, so every bit of your juice fires.
  //   const d = LD.demo(game, {moveTo(i, ms), press(i), release(i), say(text), done()})   d.stop()
  //   moveTo: glide your fake finger to cell i over ms. press/release: show the finger pressing. say: caption text.
  //   moveToLine(kind, index, ms) (optional): glide the finger to a row/column arrow; pressLine/releaseLine(kind, index) show the press.
  //   Order: three taps, a drag across a row, a double-tap that lands, a mistake, a long-press, a hint, then it solves to the win.
  // ------------------------------------------------------------------------------------------------------------------
  LD.demo = function (game, hooks) {
    hooks = hooks || {};
    const H = (k, ...a) => { try { if (hooks[k]) hooks[k](...a); } catch (e) { console.error(e); } };
    const n = game.n;
    let alive = true, tm = 0;
    const steps = [];
    const wait = (ms) => steps.push({ t: 'wait', ms });
    const say = (s) => steps.push({ t: 'say', s });
    const plan = { taps: [], drag: [], wrong: -1 };
    // three non-solution cells in the middle rows for taps
    const nonSol = [];
    for (let i = 0; i < game.N; i++) if (!game.isSolution(i)) nonSol.push(i);
    // a drag run: the longest run of non-solution cells in one row
    let best = [];
    for (let r = 0; r < n; r++) { let run = []; for (let c = 0; c < n; c++) { const i = r * n + c; if (!game.isSolution(i)) { run.push(i); if (run.length > best.length) best = run.slice(); } else run = []; } }
    plan.drag = best.slice(0, Math.min(best.length, Math.max(3, n - 2)));
    plan.taps = nonSol.filter((i) => !plan.drag.includes(i) && game.rc(i).r !== game.rc(plan.drag[0]).r).filter((_, k) => k % 3 === 1).slice(0, 3);
    say('Tap a square to cross it out'); wait(600);
    for (const i of plan.taps) steps.push({ t: 'tap', i });
    wait(500); say('Slide to paint crosses'); wait(500);
    steps.push({ t: 'drag', cells: plan.drag }); wait(700);
    steps.push({ t: 'solve' });
    let si = 0, solved = 0, didWrong = false, didLong = false, didHint = false;
    function finger(i, ms) { H('moveTo', i, ms); return ms; }
    function run() {
      if (!alive || game.won) { if (game.won) H('done'); return; }
      if (game.over) { H('done'); return; }
      const s = steps[si];
      if (!s) return;
      if (s.t === 'wait') { si++; tm = setTimeout(run, s.ms); return; }
      if (s.t === 'say') { H('say', s.s); si++; tm = setTimeout(run, 0); return; }
      if (s.t === 'tap') {
        const d = finger(s.i, 380);
        tm = setTimeout(() => { if (!alive) return; H('press', s.i); game.tap(s.i); tm = setTimeout(() => { H('release', s.i); si++; tm = setTimeout(run, 260); }, 120); }, d);
        return;
      }
      if (s.t === 'drag') {
        const cells = s.cells.filter((i) => game.cells[i] === CELL.EMPTY);
        if (!cells.length) { si++; run(); return; }
        const d = finger(cells[0], 420);
        tm = setTimeout(() => {
          if (!alive) return;
          H('press', cells[0]); game.tap(cells[0]); game.beginStroke(cells[0]);
          let k = 1;
          const go = () => {
            if (!alive) return;
            if (k >= cells.length) { game.paintEnd(); H('release', cells[cells.length - 1]); si++; tm = setTimeout(run, 400); return; }
            finger(cells[k], 130); tm = setTimeout(() => { game.paintEnter(cells[k]); k++; go(); }, 130);
          };
          tm = setTimeout(go, 120);
        }, d);
        return;
      }
      if (s.t === 'solve') {
        if (game.over) { H('done'); return; }
        // scripted beats along the way: the 2nd placement is preceded by a mistake, the 3rd uses a long press, the 4th is a hint
        if (solved === 1 && !didWrong) {
          didWrong = true;
          let w = -1;
          for (let i = 0; i < game.N; i++) if (game.cells[i] === CELL.EMPTY && !game.isSolution(i) && game.pieceAttacking(i) < 0) { w = i; break; }
          if (w >= 0) {
            H('say', 'Oops! A wrong spot costs a life');
            const d = finger(w, 500);
            tm = setTimeout(() => { if (!alive) return; H('press', w); game.tap(w); tm = setTimeout(() => { game.doubleTap(w); H('release', w); tm = setTimeout(run, 1100); }, 110); }, d);
            return;
          }
        }
        if (solved === 3 && !didHint) {
          didHint = true; H('say', 'Stuck? Ask for a hint'); H('hint');
          tm = setTimeout(() => { if (!alive) return; const r = game.hint(); if (r && r.kind === 'place') solved++; tm = setTimeout(run, 1200); }, 700);
          return;
        }
        const d0 = game.nextDeduction();
        if (!d0) { H('done'); return; }
        if (d0.kind === 'cross') {
          // show the elimination as a quick tap
          const d = finger(d0.i, 300);
          tm = setTimeout(() => { if (!alive) return; H('press', d0.i); game.tap(d0.i); tm = setTimeout(() => { H('release', d0.i); tm = setTimeout(run, 220); }, 100); }, d);
          return;
        }
        const i = d0.i;
        if (solved === 0) H('say', 'Double-tap to drop a performer');
        else if (solved === 2 && !didLong) H('say', 'Or press and hold');
        else if (solved === 4) H('say', 'Every performer adds a layer to the loop');
        const longPress = solved === 2 && !didLong;
        if (longPress) didLong = true;
        const d = finger(i, 450);
        tm = setTimeout(() => {
          if (!alive) return;
          H('press', i);
          if (game.cells[i] !== CELL.EMPTY) { game.tap(i); if (game.cells[i] !== CELL.EMPTY) game.tap(i); }
          game.tap(i);
          tm = setTimeout(() => {
            if (!alive) return;
            if (longPress) { game.revertLastTap(i); game.place(i); } else game.doubleTap(i);
            H('release', i); solved++;
            if (!game.opts.autoCross && !game.won && solved <= 2) {
              const rc = game.rc(i);
              const arrow = (kind, idx, then) => {
                if (!alive) return;
                const d2 = hooks.moveToLine ? (hooks.moveToLine(kind, idx, 420), 420) : finger(kind === 'row' ? idx * n : idx, 420);
                tm = setTimeout(() => { if (!alive) return; H('pressLine', kind, idx); game.crossLine(kind, idx); tm = setTimeout(() => { H('releaseLine', kind, idx); tm = setTimeout(then, 380); }, 110); }, d2);
              };
              tm = setTimeout(() => { H('say', 'Tap an arrow to cross out the whole line'); arrow('row', rc.r, () => arrow('col', rc.c, run)); }, 700);
              return;
            }
            tm = setTimeout(run, game.won ? 200 : 900);
          }, longPress ? game.opts.longPressMs : 110);
        }, d);
      }
    }
    tm = setTimeout(run, 300);
    return { stop() { alive = false; clearTimeout(tm); } };
  };

  // ------------------------------------------------------------------------------------------------------------------
  // JUICE HELPERS
  // ------------------------------------------------------------------------------------------------------------------
  LD.ease = {
    linear: (t) => t,
    outQuad: (t) => 1 - (1 - t) * (1 - t),
    outCubic: (t) => 1 - Math.pow(1 - t, 3),
    outQuint: (t) => 1 - Math.pow(1 - t, 5),
    inOutSine: (t) => -(Math.cos(Math.PI * t) - 1) / 2,
    outBack: (t, s) => { s = s === undefined ? 1.70158 : s; const c3 = s + 1; return 1 + c3 * Math.pow(t - 1, 3) + s * Math.pow(t - 1, 2); },
    outElastic: (t) => (t === 0 || t === 1 ? t : Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * (2 * Math.PI) / 3) + 1),
  };
  LD.reducedMotion = !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  // shake a WRAPPER element (never the element you hit-test against): s = LD.shaker(el, {px: 10, deg: 1.5, decay: 1.8}); s.add(0.3)
  LD.shaker = function (el, o) {
    o = Object.assign({ px: 10, deg: 1.5, decay: 1.8 }, o || {});
    let trauma = 0, raf = 0, last = 0, t = 0;
    function frame(ts) {
      const dt = last ? Math.min(0.05, (ts - last) / 1000) : 0.016; last = ts;
      trauma = Math.max(0, trauma - o.decay * dt); t += dt * 30;
      const s = trauma * trauma;
      el.style.transform = s > 0.0005 ? 'translate(' + (o.px * s * Math.sin(t * 1.7)).toFixed(2) + 'px,' + (o.px * 0.8 * s * Math.sin(t * 2.3 + 1)).toFixed(2) + 'px) rotate(' + (o.deg * s * Math.sin(t * 1.1 + 2)).toFixed(3) + 'deg)' : '';
      if (trauma > 0) raf = requestAnimationFrame(frame); else { raf = 0; last = 0; }
    }
    return {
      add(a) { if (LD.reducedMotion) a *= 0.3; trauma = Math.min(1, trauma + a); if (!raf) raf = requestAnimationFrame(frame); },
      get trauma() { return trauma; },
    };
  };
})();
