// Builds the shared scripts at the repo root: loopdoku-core.js, loopdoku-levels.js, loopdoku-meta.js.  Usage: node tools/build.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url)), root = path.join(here, '..');
const core = fs.readFileSync(path.join(here, 'loopdoku-core.src.js'), 'utf8').replace('/*PUZZLES*/[]', fs.readFileSync(path.join(here, 'showcase.json'), 'utf8').trim());
fs.writeFileSync(path.join(root, 'loopdoku-core.js'), core);
const lv = JSON.parse(fs.readFileSync(path.join(here, 'levels.json'), 'utf8'));
for (const id in lv.packs) lv.packs[id] = lv.packs[id].map(({ n, rows, sol }) => ({ n, rows, sol }));
fs.writeFileSync(path.join(root, 'loopdoku-levels.js'), '/* LoopDoku level packs, generated by tools/gen_levels.mjs: every puzzle has one solution and needs no guessing. */\nwindow.LD_LEVELS = ' + JSON.stringify(lv) + ';\n');
fs.copyFileSync(path.join(here, 'loopdoku-meta.src.js'), path.join(root, 'loopdoku-meta.js'));
const count = Object.values(lv.packs).reduce((a, p) => a + p.length, 0);
console.log('built core, meta and', count, 'levels');
